### ISSUE TITLE
Centroid diagnostic plots for FFI are ON by default

### ISSUE THREAD

**Issue by jorgemarpa** [SSDataLab/psfmachine#23]
Need to add a keyword argument that allows the user to control if these diagnostic plots are created or not.

![image](https://user-images.githubusercontent.com/10449555/126410827-c5fffd79-26c6-4142-928c-52207120fa11.png)

**Comment by christinahedges** [comment]
While we're keeping track of small issues like this, this progress bar never does anything for me:

![image](https://user-images.githubusercontent.com/14965634/126411403-f5c88886-e6da-4ff1-a59f-2a7ff9c38511.png)

It's always empty

And I'm not sure why it's calculated twice?

**Comment by jorgemarpa** [comment]
> While we're keeping track of small issues like this, this progress bar never does anything for me:
> It's always empty

I think this is because I switch to `tqdm.auto` which suppose to detect if the code is running in a notebook or terminal environment and adjust the style of the progression bar. In my case works fine. Let's see if switching back to just `tqdm` fix it for you.

> And I'm not sure why it's calculated twice?

Because `build_shape_model()` calls `_get_source_mask()` which has to recompute the delta arrays to correct the centroid offsets. 
But now I think this could be done in a more efficient way avoiding that for loop and just subtracting the offset term to the original `dra, ddec`. I'll work on an improvement for this
