### ISSUE TITLE
PSFMachine perturbation matrix needs a refactor

### ISSUE THREAD

**Issue by christinahedges** [SSDataLab/psfmachine#55]
In the future, we need to refactor our perturbation matrix API. 

- `A`, `A_cp`, `A2`, and `A3` are impossible to understand when reading the code
- We ideally need some sort of perturbation matrix class which deals with the building and shaping of this high dimensional matrix
- This would let us append other vectors (e.g. engineering data)
- This class might have methods for "cleaning" the input vectors (detrending by polynomials, fitting with splines to make smooth etc)
- This would let us have some function like `mac.mean_perturbed_model(time=...)` which would give us the flux from the perturbed model!

This is currently NOT a priority.

**Comment by christinahedges** [comment]
We also need to add in tests for the masking to show they mask the correct pixels (e.g. saturated pixel mask)

**Comment by jorgemarpa** [comment]
This was implemented in PRs #59 and #60.
Closing.
